docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - { Intro: intro.md }
    - Reference:
      - { 'Block Ciphers': block-cipher.md }
      - { 'Encrypting Files': files.md }
      - { 'Hybrid Cryptosystem': hybrid.md }
      - { 'Key Derivation': key-derivation.md }
      - { Passwords: password.md }
      - { 'Public Key Cryptography': public-key.md }
site_name: laminas-crypt
site_description: Laminas\Crypt
repo_url: 'https://github.com/laminas/laminas-crypt'
